### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by ghost** [RocketMod/Rocket#526]
I have a problem with the vanish command. Each time I teleport to someone in vanish mode, I am visible for a short time. What happens: Ouh, there is an admin. Stop glitching guys.
Hope it can be fixed. :)

**Comment by cartman-2000** [comment]
There was a "fix" for that at one time, but it was buggy so it was rolled back. It would cause you to get stuck in the ground when you tried to teleport to someone with vanish enabled.

I wonder if you could make it so that the /tp command will teleport you to one unit behind the player in the opposite direction to where the player is looking when you're in vanish mode? It's kind of a cheap way of doing it, but at least you shouldn't be visible to the player you're teleporting to. The only problems I can think of with this is that it would be possible to get stuck in a wall or some other object if they have their back up against it when you teleport to them, and you would still be visible to other players for a short period of time.

**Comment by Freenex159** [comment]
Ye I had the same idea but I thought that it can be fixed. Anyway, thats a good idea and in case you stuck in a wall you can just teleport twice. Another way maybe is to teleport under the player and then to the player. Am I visible then?

**Comment by cartman-2000** [comment]
That teleport under is, I think, how it was done before, which is why you would get stuck in the ground when you teleported to someone.

**Comment by fr34kyn01535** [comment]
@cartman-2000 yes, i could calculate the new position based on the direction you are facing, but if you are teleported from that direction you will still see him flingin...

**Comment by falsechicken** [comment]
Can you get the facing direction of the target player? If so you could use that instead. Although others around them could still see you.

**Comment by fr34kyn01535** [comment]
How does this work now?
