### ISSUE TITLE
Unturned Server Freezes Entire Computer

### ISSUE THREAD

**Issue by axiomaticTwist** [RocketMod/Rocket#573]
After the latest release of the Rocket to fix console commands (724), I run my server and... It freezes my computer. I've restarted my computer 4 times already, to no avail. Anything to help would be great. I'm running my MySQL Database server on the same computer. I notice that I'm running out of RAM upon startup when everything is loaded in. Should I try reinstalling MySQL?

**Comment by cartman-2000** [comment]
What is the size of your map's barricades file? It sounds like it has gotten corrupted and has blown up to an enormous size, which would eat up enormous amounts of ram. I've had this happen to me a number of time on my server, each time it would make the server use about 8-12GB of ram after startup(I have 32GB of ram on the system that my server's are running on.) and the barricades file would be around 4-7gb in size.

If it is due to a corrupted barricades file, then it isn't an issue with the update to Rocket that is causing your problem.
