### ISSUE TITLE
can someone please help

### ISSUE THREAD

**Issue by jonthegreat** [RocketMod/Rocket#588]
i'm trying to install the /home plugin yet i don't know how to make it so normal players can do /home please link a video to help me ty!

**Comment by Larsdude** [comment]
When you download the plugin, it should contain a .dll file. Here's a quick step-by-step of how to install it:
1. place the <plugin>.dll file in your Unturned/servers/<servername>/rocket/plugins folder.
2. Run the server once and close it. This is so that .dll file integrates with your server and creates new folers and files.
3. In your Unturned/servers/<servername>/rocket/plugins folder there should be a new folder with the same name as the plugin's .dll file. Inside there are the config files. Modify them as you see fit, to the extent that the plugin allows.
4. In your Unturned/servers/<servername>/rocket folder there will be a permissions.xml file. You will probably need to right-click and open with notepad, notepad++, or something along those lines.
5. The plugin's homepage probably has an example of what to do with the permissions file, but if they don't, in the list of similar-looking lines in the group "default" or "Guest", add this line:
<Command>home</Command>

Sorry there isn't a video for this, but hopefully this will be close enough.
