### ISSUE TITLE
Weird connecting issue (infinite loading screen)

### ISSUE THREAD

**Issue by dobegor** [RocketMod/Rocket#601]
We maintain a few servers with Rocket on home server, and then we decided to expand, with a few droplets at Digitalocean.

Using the latest Ubuntu (15.10), nobody can connect to the server.
Of course, there are absolutely no portforwarding issues, nor any log entries upon connecting.

No firewall installed/enabled, according to ``` netstat -tulp``` command all ports are binded normally by server, no routing issues (other apps with both tcp/udp are working well).

Latest availible ```mono-runtime``` instaleld.

The client is just stuck at infinite loading screen. Always. Until Alt+F4, so no timeout message.
We tried running on a latest CentOS with the same result. Absolutely nothing weird in logfile to post here, just usual server startup log. Shutdowns nomally, doesn't lag/freeze, plenty of RAM/CPU free.

Home server is running Ubuntu 14.04, but all the same configuration (we even tried to just plain copy the server folder and runnning it on DO vps, with same issue).

Please, suggest me what should I do to investigate this issue.

**Comment by falsechicken** [comment]
When I got this issue re-validating/re-installing using steam fixed it. Or trying a fresh world save.

**Comment by dobegor** [comment]
Well, I will try it too.
But please keep the issue open until we can get this investigated and fixed.

**Comment by dobegor** [comment]
To devs: if you can't reproduce it, contact me here and I'll give you access to one of our testing droplets to look at it. That's the best option because there are really no logs  I can find about this issue.

**Comment by falsechicken** [comment]
I have reproduced this before but only on accident. Usually its an incorrect Rocket install or corrupted files.

**Comment by exploser** [comment]
As a co-host of the aforementioned server (droplet), I tried both clean Rocket installation with no plugins/mods whatsoever and a copy of currently working server with all the data: the results were identical. Tried on both Ubuntu 15.10 x86 and x64. RCON connections work just fine, client connections seem to happen, but it looks like no data is ever transmitted - the server console remains quiet and the client just hangs on "Loading" forever.
It was mentioned that the 'home' server was running Ubuntu 14.10, which is actually incorrect - it is 15.10 x64, so release-related issues don't seem to apply.

**Comment by falsechicken** [comment]
Hmm... I do not know the cause of this issue. I use 15.10 x64 (Ubuntu Mate) and whenever I got this issue the advice I got from fr34kyn01535 was to reinstall. I do not really know how to troubleshoot it. As I have said before reinstalling always fixed it so it was a non-issue. I always considered it some kind of user error.

I wonder if this happens without Rocket? Although I do not even know if the Unturned server will run properly on Linux without Rocket. Everyone I had seen who tried said it didn’t work.

**Comment by dobegor** [comment]
@falsechicken No, we haven't reinstalled client, but none of our admins can join the server, no matter what platform they are using (Windows/Linux).

There is update from Unturned devs, and they mentioned 'added logs on connecting' in their changelog. So we will try it tomorrow and see what's there and update the issue.

**Comment by dobegor** [comment]
Can we get some feedback from devs?
The issue is still there.

**Comment by dobegor** [comment]
@falsechicken 
we tried using old 14.04 and it just worked.
but unfortunately, 
1) DO doesn't provide 14.04 images
2) we don't know why it worked.

please tell me if you can ssh our test servers and debug it yourself.
I don't have real experience developing/debugging c# and other .net stuff

**Comment by fr34kyn01535** [comment]
Well, first off, this is not a Rocket issue, so totally unrelated to this forum. We do not officially support Linux, we just offer a build that should work under the ideal environment we declared, and having installed all the packages we advise in the scripts. We simply can't promise compability to everything with a linux kernel ;) 

Steamcmd is pretty unreliably, sometime it hangs, sometime it corrupts files. The first thing you should test on a fresh environment is:

1. Setup dependencies & xserver
2. Clear steamcmd data, let it redownload itself, then the game
3. Start Unturned and read the log file in a new tab (tail -f..)
(4.) You could install Rocket, you could also skip this step if you really think rocket is the culprit
5. You should be able to track down any issues now from reading stdout or the log file. 
6. Additionally the syslog can be checked for issues with xserver (permission issues for example)

Only if you experienced problems in a rocket environment vs a vanilla environment, the issue is to be reported on this bugtracker and i will look into it..

To iron out issues with no-root users i'd try it as root first, other users have to be allowed to use xserver, chowned to the files etc.. I DONT RECOMMEND USING ROOT IN PRODUCTIVE ENVIRONMENT tho, for obvious reasons..

One more thing, "vservers", like guests in a kvm have limited xserver support, i don't know about your droplets, but that could be an issue.

**Comment by devadmuho** [comment]
I've encountered the exact same issue with DO. If I try to launch the Unturned server on its own, it Segfaults. If I try to launch the Rocket server, it loads fine, but running debug shows no data being exchanged and anybody who tries to connect gets an infinite loading screen where the game is frozen but the mouse cursor still works in the game.
