### ISSUE TITLE
/noclip & /fly

### ISSUE THREAD

**Issue by Ejraiel** [RocketMod/Rocket#638]

**Comment by Ejraiel** [comment]
This is a suggestion for new commands, not a bug report.

**Comment by falsechicken** [comment]
I am actually not sure these commands are even possible without a client mod....

**Comment by Ejraiel** [comment]
Hah, didn't even think about the client side on this one.

Flying would be more like "constant falling".

**Comment by falsechicken** [comment]
One issue I foresee is that Rocket, being a server mod, Cannot poll input from the client. So I foresee that there would need to be commands for up, down, forward, back, etc. And I do not think it would be a useful feature to have to type a direction every time you want to move. Lol.

**Comment by Ejraiel** [comment]
Odd.

I'd expect that serverside mods would know what the client is sending, since the client's movement is known by the server.

But yeah, regardless, the client by default can't fly or clip; so even though the server could simply stop policing a specific player's movement / location, that player's client would need to perform the movement.

With flying, that would mean they'd constantly be falling, seeming to teleport back up to where the server is allowing their location to be in flight. As for noclip, well, there could be a "jump" command to move towards the cursor a specified distance regardless of obstructions, but yeah, the desire was simply moving through things, which again would require the client to be modded.

**Comment by falsechicken** [comment]
Yeah. Hovering in the air would not be a problem. Simply set their position constantly. And since you can control movement direction while falling you probably could (slowly) fly. A plug-in could do this. But as was said you could need a command to set height and land.

A jump command is also possible but I do not know how to handle getting stuck in terrain/objects. 

Take everything I say with a grain of salt as I really no longer play the game or develop anything Rocket related.
