### ISSUE TITLE
Can't use the telnet to connect the server.

### ISSUE THREAD

**Issue by 7gugu** [RocketMod/Rocket#757]
When I use the php code like:exec or system to start the server.It would't allow the telnet connect to the server.How can I solve it?

**Comment by fr34kyn01535** [comment]
Sure it would, since you run it as www-data,or what user ever invoked php, you probably can't use a port below 1024 etc..  Also make sure the process is staying alive. A solution would be to create a screen and start it there...  This is not a bug tho, rcon works fine. Troubleshoot it in the forum please.
