### ISSUE TITLE
At a loss, /storm no longer works

### ISSUE THREAD

**Issue by Joystation** [RocketMod/Rocket#807]
Originally my day/night cycle wasn't working properly as well as this. I've fixed the day/night issue, but still cannot trigger rain with /storm, nor will it rain on its own. Scouring google has only led me to threads identical to this: https://github.com/RocketMod/Rocket/issues/793 where the question was asked then ignored. 

If you've had this issue, what did you do to fix it?

**Comment by fr34kyn01535** [comment]
Those are unturned commands aren't they? Seems like an unturned issue..

**Comment by Joystation** [comment]
Those would be the rocket commands, and this issue only affects servers using rocket. So, it would seem that it's a rocket issue as it is not the game developer's responsibility to make sure that the mod is compatible. Thanks for your no effort response though, maybe your vast knowledge can be used on the other 20 open issues over the past year now. :)

**Comment by fr34kyn01535** [comment]
Well see. The main issue here is people blaming Rocket for everything. If you would have a kind look at https://github.com/RocketMod/Rocket.Unturned/tree/master/Rocket.Unturned/Commands it is **NOT** a Rocket command. Feel free to support me fixing the other issues with me and don't wast my time please.

**Comment by fr34kyn01535** [comment]
You can also look at the git history if you so wish and see that /storm has **NEVER** been a Rocket command.

**Comment by Joystation** [comment]
While I'm doing that, have a look at how Rocket renders "@" useless and forces the user to use its format instead. Yes, there is now support for "/" in Unturned now after a quality of life update. While Rocket is nice, don't get me wrong, it's breaking servers— I'll repeat myself, this issue only occurs on servers running Rocket. Be my guest though if you want the only fix for this to remain, "Remove Rocket,", I mean, you did close a topic that asked the community: "If you've had this issue, what did you do to fix it?" because it made your mod look bad. 

Your TL;DR: Sorry your mod is broken, we'll let you know when we fix it for you.

**Comment by fr34kyn01535** [comment]
Well, you seemed to have magically solved the day/night, i believe in you.

**Comment by fr34kyn01535** [comment]
Just tested it on vanilla and a naked rocket - works flawless. Thanks for wasting more of my time.
What map are you using, what plugins?

**Comment by leo65** [comment]
/storm command working fine in my rocket servers

**Comment by rwalkos** [comment]
Hey Joystation. I have ran into a similar problem with day / night cycle and storm. I'll give you all the information I have come up with.

First I was using wreckingball to auto blow up vehicles on a timer and after update 3.15.11.0 OR 3.15.13.0 (I'm really can't remember how long I have been fighting this)  the timer for wreckingball started acting funny. Sometimes it would delete only 1 vehicle others 2 or 3 even though there were many more to be deleted.

I since switched to uEssentials for my vehicle wipes and started having sporadic day / night cycles and sometime weather. Some players would be effected and others wouldn't. Some players would report day and others night while raining. The command it uses to remove vehicles is /clear ev. I have started with a freash OS install, steamcmd, and Rocket with the only plugin being uEssentials. I did this with no mods or maps to test out the /clear ev command to eliminate any other possible problems.

To test I used map PEI and gave myself admin rights. I logged onto the server and ran around spawning vehicles and then using /clear ev. For awhile I didn't notice anything wrong but after about 30 minutes of doing that the problem arose.

Soon as I noticed a slight but instant time change I tried using /day and /night. And sure enough it was broke and didn't work right.

Really I don't have a conclusion on what is exactly causing the issue but I figured  I would post my experiences here since this is one of the few places I have seen someone talk about something similar. I have submitted an issue on the uEssentials github page and hope it gets fixed soon. Really I would love a plugin that acts like wreckingball does but instead of blowing up the vehicle is completely removes is as /clear ev does.

Best of luck to you all and try to be a little nicer Joystation, and unless you are willing to pay these fine folks a living salary you really have no right to talk to them the way you have.
