### ISSUE TITLE
I cant play unturned with Rocket 

### ISSUE THREAD

**Issue by catttys** [RocketMod/Rocket#830]
I try  to create an unturned server with rocket but it doesnt let me start the game screenshot : bb3c0e208021cbe5b6db13aba551984c

**Comment by catttys** [comment]
https://gyazo.com/bb3c0e208021cbe5b6db13aba551984c

**Comment by KEJustusKE** [comment]
You must make a seperate folder with the unturneddatas for your server. Because if you install rocket in your folder which you use to play it don´t works.

**Comment by persiafighter** [comment]
@catttys as @KEJustusKE said, you **need** a separate unturned folder for your game and your server. Having both on the same location + with rocket installed will just give you that error. Plus, there was a warning given out by rocket that still is up that **you can not** run unturned in play mode with **rocket installed**. So simply create a separate folder for your servers and install rocket there, whilst run unturned from the main game (also, uninstall rocket from the main folder that you will play from).

**Comment by iMrShadow** [comment]
I had the problem too. But how can i play Unturned without deleted it and loosing all the skins and maps.
Here`s what i did. I made a new folder and copied the Unturned files(with rocket). Then i deleted the files in the main folder(the rocket files). And still can`t play it because it can`t load the menu. I will sent a photo. And i see the picture forever.
![20160923141304_1](https://cloud.githubusercontent.com/assets/22393274/18784057/3ad74420-8198-11e6-8ef1-967b752732cc.jpg)

**Comment by iMrShadow** [comment]
Ok i know what to do. You need to go to Steam Library->Games->Unturned Right Click->Properties->Local Files-> Verify the game inche(small version). It will remove Rocket from the folder and you can play it. And next time follow the steps ;)

**Comment by catttys** [comment]
Thanks m8

Den fredag den 23. september 2016 skrev iMrShadow <notifications@github.com
