### ISSUE TITLE
Can't use the RocketMod website?? (I have literally no idea where else to say this)

### ISSUE THREAD

**Issue by cha0sbuster** [RocketMod/Rocket#836]
I'm trying to download Rocket for my server that I run for my friends but when I try to do any variation of rocketmod.net I get a "Refused to Connect" error.
https://gyazo.com/83389ed655814a97612ebeb46471f9b2

Does anybody know how to fix this, or could somebody provide a mirror to the most recent version of Rocket?

Sorry if this is impermissible because it's not about the mod itself but I have no idea where else I could put this to get help.

**Comment by Redwallfred** [comment]
Yeah, im experiencing the same problem, and so far havent been able to find any mirror or copy from someone, hopefully this will be fixed soon, otherwise you may need to run your server as vanilla, if you do find anything that does work or a working version please let me know, and if i find one, ill be sure to comment it here, or start a new one somewhere.

**Comment by takahashitakeshi** [comment]
me too

**Comment by Cyboulette** [comment]
Updated on the official website :
"We are getting many reports of people that can't connect to this website due to multiple incidents in the OVH network. Our server provider is notified, we are expecting the fix soon. 
Affected host domains: rocketmod.net, api.rocketmod.net, dev.rocketmod.net, ci.rocketmod.net
Affected host IP adresses: 149.202.245.110, 178.32.57.167, 92.222.235.176 

Note that we don't block IP addresses unless they are spamming the API. In that case the API key will also be disabled."

**Comment by cha0sbuster** [comment]
Yeah a friend told me it seems like it's on their side.
Hoping for a fix soon. Need an autosave plugin because I keep forgetting to
save the server before shutting it down lmao

**Comment by cha0sbuster** [comment]
We're back up!
