### ISSUE TITLE
Does not start RocketLauncher.exe [LINUX]

### ISSUE THREAD

**Issue by typicalcoder** [RocketMod/Rocket#880]
UPD https://github.com/RocketMod/Rocket/issues/878

I began to look for the reason why "start.sh" hangs. When you run the command "mono RocketLauncher.exe" - is an eternal starting the program. What to do?

**Comment by fr34kyn01535** [comment]
No. This is still not the right place to discuss your problem. This 'issues'  is the place to report issues to the maintainer. I am NOT officially supporting since I simply don't have the time so search a solution in the forums or come with a proper bug report. Rocket not working for some unknown reason on some unknown operation system is NOT an issue to me.

**Comment by fr34kyn01535** [comment]
And another thing, don't reopen issues I closed by recreating them. Issues are reopened if they turned out to be a bug report.
