### ISSUE TITLE
Ranger Weapons not working (nykorev, dragonfang, matamorez, callingcard)

### ISSUE THREAD

**Issue by digaspirate** [RocketMod/Rocket#882]
only some weapons like the nykorev, matamorez and calling card and bugging... people try to shoot, nothing happens unless the noise for the people that shoots, no blood splashes, and the other people only see him punching

**Comment by fr34kyn01535** [comment]
We use github to track repeatable bugs, and feature requests. 
The scenario you've described seem to not be caused by a bug in Rocket itself.
Please consult [this guide](https://github.com/RocketMod/Rocket/wiki/Fixing-Issues) to figure a solution for your problem.
You can also create a new topic in [the support section on our forum](https://rocketmod.net/viewforum.php?f=7). 
If you can reproduce the bug in Unturned without Rocket being installed you may report it directly to the [Unturned developers](https://github.com/SmartlyDressedGames/Unturned/issues).
Feel free to reopen this issue if you can bring up new details on the topic.
