### ISSUE TITLE
Rocketmod not working for windows 8.1

### ISSUE THREAD

**Issue by SurvivorGodz** [RocketMod/Rocket#885]
I tried downloading it, I tried extracting it to my server folder, but it just isnt working. It wont work in servers, the error doesnt appear and I don't know what to do.

**Comment by fr34kyn01535** [comment]
We use github to track repeatable bugs, and feature requests. 
The scenario you've described seem to not be caused by a bug in Rocket itself.
Please consult [this guide](https://github.com/RocketMod/Rocket/wiki/Fixing-Issues) to figure a solution for your problem.
You can also create a new topic in [the support section on our forum](https://rocketmod.net/viewforum.php?f=7). 
If you can reproduce the bug in Unturned without Rocket being installed you may report it directly to the [Unturned developers](https://github.com/SmartlyDressedGames/Unturned/issues).
Feel free to reopen this issue if you can bring up new details on the topic.
