### ISSUE TITLE
Erro loading plugin in linux

### ISSUE THREAD

**Issue by rube200** [RocketMod/Rocket#890]
Can someone help me?
I have two first ones I have a long time but the second only started recently and is what prevents you from loading the plugins in linux.
Can help me?

First:

System.SystemException: Error running gmcs: Cannot find the specified file
  at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compil$
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDo$
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFile (System.CodeDom.Com$
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Ser$
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Obj$

Second:

ArgumentException: An element with the same key already exists in the dictionar$
Rocket.Core.Plugins.RocketPluginManager.loadPlugins ()
Rocket.Core.Plugins.RocketPluginManager.Start ()

**Comment by DoubleLee** [comment]
I have been banging my head against the wall on this one, pulled and recompiled all of my plugins rocket and uessentials.  In the end I found the problem after 5 hours.

The problem was the uessentials unzipped folders in the update folders and/or a weird shortcut that popped up in the libaries folder to one of these unzipped folders. This led to multiple uessentials dll's being loaded.

**Comment by rube200** [comment]
OK the second error I got fix and already loads the plugins but someone could explain to me what is the first one?

Thanks

**Comment by fr34kyn01535** [comment]
You can ignore the first error.
