### ISSUE TITLE
Server don't show in the list till I Join 

### ISSUE THREAD

**Issue by Sugarsz** [RocketMod/Rocket#892]
Vanilla server works fine and everyone can join 
but with rocket the server only show in the list if i Join first but only for like 5 mins 
after a while the server don't show in the list again and I need to disconnect and connect to the server show again also I think I am the first person having this issue never see a server with this bug

**Comment by cartman-2000** [comment]
Do you happen to have the max players on the server above 24 players? That would cause it to not show up in the internet tab in the in-game server browser. 

Nelson had made it so that "high slot" server's won't appear on the in-game server list, however the high slot server should still show up fine in-game in the favorites tab, if you have them there, and in the steam server browser(The one that you can use from the steam client.).
