### ISSUE TITLE
Error after update.

### ISSUE THREAD

**Issue by NmChrisV** [RocketMod/Rocket#896]
After the 3.17.16.0 I've been getting this error in my console, and my server is constantly crashing, here is the log. http://pastebin.com/NavDRAgD Not really sure what to do to fix this, but been working on it for about 12 hours.

**Comment by KEJustusKE** [comment]
Could you make a picture of your Permissions.config.xml? Maybe is something wrongthere.

**Comment by NmChrisV** [comment]
Here's my permissions. http://pastebin.com/3DYnGLAM They were working before the update, and whenever I change them I validate my XML.

**Comment by KEJustusKE** [comment]
Hmm I can´t see any mistake and I think you already tried to remove the prefix/suffix for the player "76561198136976221". And the Permissions.config work well for me. Which plugins do you use?

**Comment by NmChrisV** [comment]
Sorry for the delay, I use uEssentials, Airdrop Manage, ZaupFeast, ZaupShop, Uconomy, WebsiteCommands, Votifier, isAbusing, VehicleEvents. I've made a completely new server, re-downloaded the plugins, re-made the permissions and moved over just the map and players data but I just got his data http://pastebin.com/qqncM5Gw.

**Comment by cartman-2000** [comment]
Can you see if removing the parent group from the main group does anything? the main group has the parent set to the main group on the server.

**Comment by fr34kyn01535** [comment]
We use github to track repeatable bugs, and feature requests. 
The scenario you've described seem to not be caused by a bug in Rocket itself.
Please consult [this guide](https://github.com/RocketMod/Rocket/wiki/Fixing-Issues) to figure a solution for your problem.
You can also create a new topic in [the support section on our forum](https://rocketmod.net/viewforum.php?f=7). 
If you can reproduce the bug in Unturned without Rocket being installed you may report it directly to the [Unturned developers](https://github.com/SmartlyDressedGames/Unturned/issues).
Feel free to reopen this issue if you can bring up new details on the topic.
