### ISSUE TITLE
Server crashing on launch

### ISSUE THREAD

**Issue by sibraxlis** [RocketMod/Rocket#902]
Im geting this error when i launch the server with latest rocket from today:
Error while compiling generated serializer
/tmp/5ec61bac/2b4172b5.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.4.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /home/euthserv/Steam/steamapps/common/Unturned/Modules/Rocket.Unturned/Rocket.Core.dll (Location of the symbol related to previous error)

**Comment by fr34kyn01535** [comment]
We use github to track repeatable bugs, and feature requests. 
The scenario you've described seem to not be caused by a bug in Rocket itself.
Please consult [this guide](https://github.com/RocketMod/Rocket/wiki/Fixing-Issues) to figure a solution for your problem.
You can also create a new topic in [the support section on our forum](https://rocketmod.net/viewforum.php?f=7). 
If you can reproduce the bug in Unturned without Rocket being installed you may report it directly to the [Unturned developers](https://github.com/SmartlyDressedGames/Unturned/issues).
Feel free to reopen this issue if you can bring up new details on the topic.
