### ISSUE TITLE
Server Bugs

### ISSUE THREAD

**Issue by Ritchi1001** [RocketMod/Rocket#907]
Hello!
 I have exactly the same issue like Jumpy. 

> Tree Bug
Report this post
Sat May 14, 2016 12:03 am

> Hey,
 have the Problem, that you cant walk near Trees. I have reinstalled the server twice, but this problem still exists. I have done a quick video to revise this problem, see here => http://puu.sh/oQSjZ/2275a30d13.mp4

My Server is currently running on "Debian 8 64bit". I have already tried the same with "Ubuntu 16.04 LTS 64bit" and I am still not able to walk near trees. 
Also I found out that Aircrafts will explode if you fly about these trees. And sometimes I one hit zombies, even if they have full life. Some Items are glitched too, some knives do no damage. I really hope you can help me!

**Comment by Trojaner25** [comment]
Please do tests to confirm that this is Rocket related.
Deinstall Rocket completly and try to reproduce it.

**Comment by fr34kyn01535** [comment]
We use github to track repeatable bugs, and feature requests. 
The scenario you've described seem to not be caused by a bug in Rocket itself.
Please consult [this guide](https://github.com/RocketMod/Rocket/wiki/Fixing-Issues) to figure a solution for your problem.
You can also create a new topic in [the support section on our forum](https://rocketmod.net/viewforum.php?f=7). 
If you can reproduce the bug in Unturned without Rocket being installed you may report it directly to the [Unturned developers](https://github.com/SmartlyDressedGames/Unturned/issues).
Feel free to reopen this issue if you can bring up new details on the topic.
