### ISSUE TITLE
Mods stopped working

### ISSUE THREAD

**Issue by JMDEMO54311** [RocketMod/Rocket#921]
More locker sizes my map and other mods stopped working for my unturned server through USO.

**Comment by Trojaner25** [comment]
How is this related to rocket?

**Comment by JMDEMO54311** [comment]
Because i am runnibg uso thru rocket it only works thru rocket byt then mods stopped working

**Comment by persiafighter** [comment]
@JMDEMO54311 USO is completely separate from rocket and VERY unstable. I don't recommend using it at all. Also, workshop mods nor USO have anything to do with rocket. They both are SEPARATE things.

**Comment by JMDEMO54311** [comment]
Download it and look in the server it runs rocket

**Comment by persiafighter** [comment]
Is it hard to understand that USO is a 3rd party software that has nothing to do with rocket?
Just in case you still wanna stick with the idea that USO is part of rocket: there's a public download for rocket in the website. What USO does is download it and install it in your server. 
This is their website: https://unturned-server-organiser.com/
This is rocket's website: https://rocketmod.net/
According to the imprints of both websites (due to german law) (USO's imprint: https://unturned-server-organiser.com/imprint.php) (Rocket's imprint: https://rocketmod.net/imprint/), USO is owned by "Deventure Tech Software Solutions" and rocket is owned by "Sven Mawby Software Solutions".
THEY ARE DIFFERENT FROM EACHOTHER. They both have nothing to do with each other. USO just uses rocket when creating the server on your device because rocket is publicly available. USO did not program it. USO is NOT stable either. Some workshop bugs are due to an external program that INSTALLS the workshop content, and fails to CORRECTLY install them. 

Just to be clear on the endpoint of this discussion:
Your workshop mods not working = problem with USO, not rocket.
USO =/= Rocket.
USO -> Allows to use a GUI to host and manage servers easily. Rocket -> Allows for plugins to be loaded and includes a few extra features.

**Comment by JMDEMO54311** [comment]
I'll just get help elsewhere
