### ISSUE TITLE
unturned rocket plugins

### ISSUE THREAD

**Issue by legndkilllcamz** [RocketMod/Rocket#924]
i can make a vanilla version of unturned and people can join but once i add the plugins and rocket it does not allow anyone to join

**Comment by Tortellio** [comment]
please edit Rocket.config.xml first

**Comment by legndkilllcamz** [comment]
how do i do that

**Comment by persiafighter** [comment]
Right click on the file -> edit.

**Comment by Trojaner25** [comment]
Please attach Rocket.log. You can find it in /Rocket/Logs (the one without any numbers)

**Comment by fr34kyn01535** [comment]
We use github to track repeatable bugs, and feature requests. 
The scenario you've described seem to not be caused by a bug in Rocket itself.
Please consult [this guide](https://github.com/RocketMod/Rocket/wiki/Fixing-Issues) to figure a solution for your problem.
You can also create a new topic in [the support section on our forum](https://rocketmod.net/viewforum.php?f=7). 
If you can reproduce the bug in Unturned without Rocket being installed you may report it directly to the [Unturned developers](https://github.com/SmartlyDressedGames/Unturned/issues).
Feel free to reopen this issue if you can bring up new details on the topic.
