### ISSUE TITLE
I cant use any commands

### ISSUE THREAD

**Issue by Diafa67** [RocketMod/Rocket#996]
I cant use any commands even in the console. Anytime anyone talks, types a command, logs in, or the server is shut down I get error messages. Here is the log.
[Rocket.log](https://github.com/RocketMod/Rocket/files/1697838/Rocket.log)

**Comment by persiafighter** [comment]
Congratulations! You are our customer number _Insert random number here_ and you have won an explanation.
You see, your permissions file is broken, and you should fix it. There are XML verification tools online such as https://www.xmlvalidation.com that even show you the lines where the error was encountered (Some errors require you to read a few lines backwards until you see the mistake). Once you fix the entire permissions file, put it in the server and restart it, it should work just fine.
But since this isn't a rocket bug, it's an issue caused by you badly modifying the permissions file, I'm requesting a close.
